### ISSUE TITLE
rflink install using pip

### ISSUE THREAD

**Issue by tazounet** [aequitas/python-rflink#1]
Hello,

I tried to install rflink using pip with the command "pip install rflink" but it crashed because the tar.gz file isn't a git repository.

```
pi@raspberrypi:~/git/python-rflink $ pip install rflink
Downloading/unpacking rflink
  Downloading rflink-0.0.28.tar.gz
  Running setup.py (path:/tmp/pip-build-x9SQag/rflink/setup.py) egg_info for package rflink
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-x9SQag/rflink/setup.py", line 25, in <module>
        version=version_from_git(),
      File "/tmp/pip-build-x9SQag/rflink/setup.py", line 19, in version_from_git
        universal_newlines=True)
      File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0']' returned non-zero exit status 128
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-x9SQag/rflink/setup.py", line 25, in <module>

    version=version_from_git(),

  File "/tmp/pip-build-x9SQag/rflink/setup.py", line 19, in version_from_git

    universal_newlines=True)

  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0']' returned non-zero exit status 128

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-x9SQag/rflink
Storing debug log for failure in /home/pi/.pip/pip.log
```

Thanks !

**Comment by aequitas** [comment]
Hi, sorry for the late response, I missed the notification on this issue.

I see you are trying to install this on Python2.7. This package only support Python3.4 and up so I didn't test py2.7 installation. I will make some modifications to make clear it's python3 only.

**Comment by tazounet** [comment]
Ok, it works fine with "pip3 install rflink" (i'm on a raspberry pi).

Thanks.
