### ISSUE TITLE
mertik maxitrol G6R-H4TV21-z22 PROTOCOL issue

### ISSUE THREAD

**Issue by siggy2** [aequitas/python-rflink#51]
Hi,

I am having a similar issue as reported in different threads with the protocol using my Mertik remote as I believe users have had for other devices on rflink and HA.

here is the error log:
2020-11-16 19:19:16 DEBUG (MainThread) [homeassistant.components.rflink] Sending command: on to Rflink device: mertik_gv60_038527_13
2020-11-16 19:19:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2824163560]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/rflink/__init__.py", line 561, in async_turn_on
await self._async_handle_command("turn_on")
File "/usr/src/homeassistant/homeassistant/components/rflink/__init__.py", line 498, in _async_handle_command
await self._async_send_command(cmd, self._signal_repetitions)
File "/usr/src/homeassistant/homeassistant/components/rflink/__init__.py", line 524, in _async_send_command
await self._protocol.send_command_ack(self._device_id, cmd)
File "/usr/local/lib/python3.8/site-packages/rflink/protocol.py", line 223, in send_command_ack
self.send_command(device_id, action)
File "/usr/local/lib/python3.8/site-packages/rflink/protocol.py", line 186, in send_command
command = deserialize_packet_id(device_id)
File "/usr/local/lib/python3.8/site-packages/rflink/parser.py", line 476, in deserialize_packet_id
assert len(id_switch) < 3
AssertionError

and here is the log when I press buttons on the remote which seems to be working fine

020-11-16 19:17:32 DEBUG (MainThread) [rflink.protocol] received data: 20;01;Mertik_GV60;ID=038527;SWIT
2020-11-16 19:17:32 DEBUG (MainThread) [rflink.protocol] received data: CH=13;CMD=DOWN;
2020-11-16 19:17:32 DEBUG (MainThread) [rflink.protocol] got packet: 20;01;Mertik_GV60;ID=038527;SWITCH=13;CMD=DOWN;
2020-11-16 19:17:32 DEBUG (MainThread) [rflink.protocol] decoded packet: {'node': 'gateway', 'protocol': 'mertik_gv60', 'id': '038527', 'switch': '13', 'command': 'down'}
2020-11-16 19:17:32 DEBUG (MainThread) [rflink.protocol] got event: {'id': 'mertik_gv60_038527_13', 'command': 'down'}
2020-11-16 19:17:32 DEBUG (MainThread) [homeassistant.components.rflink] event of type command: {'id': 'mertik_gv60_038527_13', 'command': 'down'}
2020-11-16 19:17:32 DEBUG (MainThread) [homeassistant.components.rflink] entity_ids: ['switch.fireplace']
2020-11-16 19:17:32 DEBUG (MainThread) [homeassistant.components.rflink] passing event to switch.fireplace
2020-11-16 19:17:32 DEBUG (MainThread) [homeassistant.components.rflink] Fired bus event for switch.fireplace: down
2020-11-16 19:17:33 DEBUG (MainThread) [rflink.protocol] received data: 20;02;Mertik_GV60;ID=038527;SWIT
2020-11-16 19:17:33 DEBUG (MainThread) [rflink.protocol] received data: CH=13;CMD=DOWN;
2020-11-16 19:17:33 DEBUG (MainThread) [rflink.protocol] got packet: 20;02;Mertik_GV60;ID=038527;SWITCH=13;CMD=DOWN;
2020-11-16 19:17:33 DEBUG (MainThread) [rflink.protocol] decoded packet: {'node': 'gateway', 'protocol': 'mertik_gv60', 'id': '038527', 'switch': '13', 'command': 'down'}
2020-11-16 19:17:33 DEBUG (MainThread) [rflink.protocol] got event: {'id': 'mertik_gv60_038527_13', 'command': 'down'}
2020-11-16 19:17:33 DEBUG (MainThread) [homeassistant.components.rflink] event of type command: {'id': 'mertik_gv60_038527_13', 'command': 'down'}
2020-11-16 19:17:33 DEBUG (MainThread) [homeassistant.components.rflink] entity_ids: ['switch.fireplace']
2020-11-16 19:17:33 DEBUG (MainThread) [homeassistant.components.rflink] passing event to switch.fireplace
2020-11-16 19:17:33 DEBUG (MainThread) [homeassistant.components.rflink] Fired bus event for switch.fireplace: down

here is the link to the thread on letscontrolit where I got pointed here. https://www.letscontrolit.com/forum/viewtopic.php?f=12&t=8074

hope you can help!

**Comment by aequitas** [comment]
I think this has to do with the underscore in the protocol name (`Mertik_GV60`). Simmilar to the `dooya_v4` https://github.com/aequitas/python-rflink/blob/master/rflink/parser.py#L470-L472. I would have to add an exception for this. Or see if there is a way to solve this generically. I don't know when I'll be able to look into this. But feel free to post a PR with a solution if you like.

**Comment by siggy2** [comment]
Thanks for replying @aequitas . I am afraid I am not competent enough to provide a solution being a relative noob. I'd of course appreciate your help in this, but understand you'll need to prioritize

**Comment by javicalle** [comment]
I believe that #52 can do the job.

**Comment by aequitas** [comment]
#52 is merged via #53, should solve this issue. I'll make a release soon.

**Comment by aequitas** [comment]
New version is released: https://pypi.org/project/rflink/0.0.55/

If you want to use this in home assistant I suggest to create a PR on core to have the version increased, like: https://github.com/home-assistant/core/pull/39342

**Comment by siggy2** [comment]
This is awesome. Thanks both for quick turnaround. I know this is probably just going to annoy you, but I have no idea how to put together the pull request correctly.

**Comment by javicalle** [comment]
> This is awesome. Thanks both for quick turnaround. I know this is probably just going to annoy you, but I have no idea how to put together the pull request correctly.

I understand that the whole PR part can be a bit complicated, so I'm going to ask you to open an issue first. To do this you must go to the Home Assistant repository:
https://github.com/home-assistant/core/issues/new?template=BUG_REPORT.md

Let's thank @aequitas for their effort and dedication and let's continue in HA.

**Comment by siggy2** [comment]
Thanks @aequitas ! really appreciate it. @javicalle I have opened a new issue: https://github.com/home-assistant/core/issues/43687

**Comment by aequitas** [comment]
@siggy2 See it as a little nudge to get you rolling into open source development ;) Kind of like an excercise left to the reader :).

**Comment by siggy2** [comment]
@aequitas I have finally gotten the maxitrol I have to work with the rflink - alt (i.e. https://github.com/hardcodedpassword/rflink-alt). It seems the signals need repeating 10 times with a pause of 20 ms in between each burst. I suspect rflink r48 hasn't gotten that correct and though I have tried to engage with Stunteam, I have no illusions that there will be a response in this century. I therefore thought I'd experiment with trying to repeat the command when sending it to rflink with a script from HA using your integration. That was unuccesful, but I suspect it is because it waits for acknowledgement before releasing. Before I spend a lot of time experimenting, do you know how the protocol works and what delays there are when sending a command etc. Any suggestions as to what the most elegant solution would be to experiment with this?

**Comment by aequitas** [comment]
You could use the build-in repeat function: https://github.com/aequitas/python-rflink/search?q=repeat

For HA you can use the `signal_repetitions` argument: https://github.com/home-assistant/core/blob/dev/homeassistant/components/rflink/__init__.py#L46

**Comment by siggy2** [comment]
thanks a lot for the quick reply - that's helpful. Can I pass the number of repeats as part of the command sent from HA or is that manipulated somewhere else (sorry for the basic question)
also, what's the delay between the repeats?

**Comment by aequitas** [comment]
You can add it as an option to the device configuration YAML in HA.

**Comment by javicalle** [comment]
In HA, signal repetitions can be configured by device:
* https://www.home-assistant.io/integrations/switch.rflink/#signal_repetitions

I think there is not a `delay` value between the repeats, just the response time from RFLink:
* https://github.com/home-assistant/core/blob/d2c989ed934f38c86f41125e36f07f232eb25d47/homeassistant/components/rflink/__init__.py#L573-L576

**Comment by siggy2** [comment]
Thank so much for trying to help, guys. Unfortunately the use of the repetition option didn't work. I guess it is either not working because the pause between repetitions isn't correct (it seems I need ~20ms for it to work) or the plugin isn't parsing correctly. As far as I understand there is no way to send the actual raw pulse codes to the rflink? and / or define the time between repetitions? (the frustrating part is that I now know the code sequence for the commands I need)

If neither of above options work, it seems I either have to switch to rflink - alt and figure out the sequence for all my other devices and adapt / program an integration with HA or wait forever on a new release of the flink firmware. Any suggestions would we super welcome as I have spent a disproportionate amount of time to get that stupid device to work :-(
