### ISSUE TITLE
TypeError: As of 3.10, the loop parameter was removed from Event() since it is no longer necessary

### ISSUE THREAD

**Issue by javicalle** [aequitas/python-rflink#67]
From HA (where rflink is still at v0.0.58) an user has reported an issue with RFLink and Python 3.10:
* https://github.com/home-assistant/core/issues/64904

```
2022-01-25 11:31:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/rflink/__init__.py", line 274, in connect
    transport, protocol = await connection
  File "/srv/homeassistant/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 446, in create_serial_connection
    transport, protocol = await connection_for_serial(loop, protocol_factory, serial_instance)
  File "/srv/homeassistant/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 473, in connection_for_serial
    protocol = protocol_factory()
  File "/srv/homeassistant/lib/python3.10/site-packages/rflink/protocol.py", line 235, in __init__
    self._command_ack = asyncio.Event(loop=self.loop)
  File "/usr/lib/python3.10/asyncio/locks.py", line 167, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

It is a new issue?

The change in Python 3.10 as reported here: https://bugs.python.org/issue42392

I think it's been dropped at this point:
* https://github.com/aequitas/python-rflink/commit/bb99d394f828989307eb22996141fcf48cde2dc0

But, can be an issue also here?
* https://github.com/aequitas/python-rflink/blob/ddf4b91bba089b6faac75a7a40409f945e091a12/rflink/protocol.py#L235
* https://github.com/aequitas/python-rflink/blob/ddf4b91bba089b6faac75a7a40409f945e091a12/rflink/protocol.py#L236
* https://github.com/aequitas/python-rflink/blob/ddf4b91bba089b6faac75a7a40409f945e091a12/rflink/protocol.py#L258

Thanks in advanced.

**Comment by aschor** [comment]
Hi, can anything be done please ? This is blocking for actual and future home assistant versions, see 
https://github.com/home-assistant/core/pull/63678

**Comment by aequitas** [comment]
The argument was removed in this commit https://github.com/aequitas/python-rflink/commit/bb99d394f828989307eb22996141fcf48cde2dc0 so if you bump the version on HA it should work right?

**Comment by javicalle** [comment]
@aschor RFLink dependency has been bumped to v0.0.62 in HA:
* https://github.com/home-assistant/core/pull/64911

I don't know if this is still an issue (I don't run Python 3.10). 🤷🏻‍♂️

**Comment by aschor** [comment]
I guess it's OK then, I had not seen this merge, thanks
